#!/bin/bash
# Railway Environment Variable Setup Commands
# Run these commands in your terminal:

railway variables set SUPABASE_URL="https://vrrtzxgmwyfnxacqcxvz.supabase.co"
railway variables set SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZycnR6eGdtd3lmbnhhY3FjeHZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNDEzMzcsImV4cCI6MjA2NDkxNzMzN30.YmS41S2CK19hbJQ-CJZbX_0V8IGlCcQFdLoS42Dhhic"
railway variables set SUPABASE_SERVICE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZycnR6eGdtd3lmbnhhY3FjeHZ6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTM0MTMzNywiZXhwIjoyMDY0OTE3MzM3fQ.YNYaK0fJ20Szq-Es3Q-PN_OqvCay8fl4OsZ-k6UJbAM"
railway variables set SUPABASE_JWT_SECRET="gsK0/6v237LN4hVPG+PMkEwlatnVTI9A43rb+B4jWvU/XrLAhR+7d5ctiu9/dHlWbrhfMLumgO2fKy1WjxtFng=="
railway variables set DATABASE_URL="postgresql://postgres:juicwWRLD@1759@db.vrrtzxgmwyfnxacqcxvz.supabase.co:5432/postgres"
railway variables set ENVIRONMENT="production"